### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by nucliweb** [cristinafsanz/setup#1]
Hola Cristina!

Yo tengo un repo con lo que tengo configurado en la terminal (iTerm).
En los cursos online siempre me preguntaban por ello y acabé creando el repo 😅

https://github.com/nucliweb/my-terminal

**Comment by cristinafsanz** [comment]
Ah qué bien! Pues lo usaré para configurar mi terminal y lo añadiré en mi repo. Muchas gracias @nucliweb!

**Comment by nucliweb** [comment]
:)
